# Generated by Django 4.2.5 on 2023-09-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cunty',
            options={'verbose_name': 'Кунтик', 'verbose_name_plural': 'Кунтики'},
        ),
        migrations.AddField(
            model_name='cunty',
            name='add_features',
            field=models.TextField(default='', max_length=120, verbose_name='Дополнительные свойства'),
        ),
        migrations.AddField(
            model_name='cunty',
            name='code_name',
            field=models.CharField(default='', max_length=30, verbose_name='Кодовое имя'),
        ),
        migrations.AddField(
            model_name='cunty',
            name='materials',
            field=models.CharField(default='', max_length=45, verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='cunty',
            name='size',
            field=models.CharField(default='', max_length=10, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='cunty',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
    ]
