# Generated by Django 4.2.5 on 2023-09-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cunty_options_cunty_add_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cunty',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
