# Generated by Django 4.2.5 on 2023-09-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cunty_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cunty',
            name='code_name',
        ),
        migrations.AddField(
            model_name='cunty',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Название'),
        ),
    ]
