# Generated by Django 4.2.5 on 2023-09-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cunty_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='cunty',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cunty',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Размер'),
        ),
    ]
