# Generated by Django 4.2.5 on 2023-09-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cunty',
            name='seller',
        ),
    ]
