# Generated by Django 4.2.5 on 2023-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cunty_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cunty',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус'),
        ),
    ]
