# Generated by Django 4.2.5 on 2023-09-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cunty_color_alter_cunty_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cunty',
            name='size',
            field=models.CharField(default='', max_length=8, verbose_name='Размер'),
        ),
    ]
